
services:
  web:
    build: .
    command: poetry run gunicorn django_config.asgi:application  --workers 4 --threads 8 --worker-class django_config.uvicorn_worker.CustomWorker --bind 0.0.0.0:8000
    env_file:
     ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   volumes:
  #   - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  # pgadmin-data:
