# Generated by Django 5.1.7 on 2025-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationsdistance',
            name='distance_text',
            field=models.CharField(max_length=32),
        ),
    ]
