# Generated by Django 5.1.7 on 2025-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_geolocationsdistance_distance_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='input_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
