# Generated by Django 5.1.7 on 2025-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_geolocation_input_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='input_address',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
